export const CREATE_TASK_REQUEST = "CREATE_TASK_REQUEST";
export const CREATE_TASK_SUCCESS = "CREATE_TASK_SUCCESS";
export const CREATE_TASK_FAIL = "CREATE_TASK_FAIL";
export const CREATE_TASK_RESET = "CREATE_TASK_RESET";

export const EDIT_TASK_REQUEST = "EDIT_TASK_REQUEST";
export const EDIT_TASK_SUCCESS = "EDIT_TASK_SUCCESS";
export const EDIT_TASK_FAIL = "EDIT_TASK_FAIL";
export const EDIT_TASK_RESET = "EDIT_TASK_RESET";

export const LIST_TASK_REQUEST = "LIST_TASK_REQUEST";
export const LIST_TASK_SUCCESS = "LIST_TASK_SUCCESS";
export const LIST_TASK_FAIL = "LIST_TASK_FAIL";

export const GET_AI_DESC_REQUEST = "GET_AI_DESC_REQUEST";
export const GET_AI_DESC_SUCCESS = "GET_AI_DESC_SUCCESS";
export const GET_AI_DESC_FAIL = "GET_AI_DESC_FAIL";

export const TASK_DAILY_SUMMARY_REQUEST = "TASK_DAILY_SUMMARY_REQUEST"
export const TASK_DAILY_SUMMARY_SUCCESS = "TASK_DAILY_SUMMARY_SUCCESS"
export const TASK_DAILY_SUMMARY_FAIL = "TASK_DAILY_SUMMARY_FAIL"

